server:
  port: 9001


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cilicili?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xjk,929686415
  security:
    user:
      name: admin
#      password: 123456
      password: "$2a$10$UUbMgKe4ozOFfcfJcC6KoOQHLixmMNF.Evx.E5/AkidUExBGXuq6m"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  graphql:
    cors:
      allowed-methods: POST,GET,OPTIONS,DELETE,PUT
      allowed-headers: Access-Control-Allow-Origin,Content-Type,X-Requested-With,accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers
      allowed-origins: localhost:9005
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      jedis:
        pool:
          max-active: 8   #最大连接数据库连接数,设 0 为没有限制
          max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
          max-wait: 10000ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
          min-idle: 0     #最小等待连接中的数量,设 0 为没有限制

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


# springdoc-openapi swagger-项目配置
springdoc:
  group-configs:
    - group: 'client'
      paths-to-match: '/**'
      packages-to-scan: com.cilcil
  swagger-ui:
    enabled: true
    groups-order: desc



